Repository who-make-this/backend, pull requests merged in 2025-08, with the labels that each got.

#3 modify: gitignore의 마지막 빈 줄 추가
  .gitignore
Labels: Priority: Critical, Status: Review Needed, Type: Enhancement

#6 마일리지 도메인 추가
  src/main/java/university/likelion/wmt/common/querydsl/QueryDslConfig.java
  src/main/java/university/likelion/wmt/domain/mileage/controller/MileageController.java
  src/main/java/university/likelion/wmt/domain/mileage/dto/response/BalanceResponse.java
  src/main/java/university/likelion/wmt/domain/mileage/entity/MileageApply.java
  src/main/java/university/likelion/wmt/domain/mileage/entity/MileageLog.java
  src/main/java/university/likelion/wmt/domain/mileage/entity/MileageLogReferenceType.java
  src/main/java/university/likelion/wmt/domain/mileage/entity/MileageLogType.java
  src/main/java/university/likelion/wmt/domain/mileage/exception/MileageErrorCode.java
  src/main/java/university/likelion/wmt/domain/mileage/exception/MileageException.java
  src/main/java/university/likelion/wmt/domain/mileage/implement/MileageReader.java
  src/main/java/university/likelion/wmt/domain/mileage/implement/MileageValidator.java
  src/main/java/university/likelion/wmt/domain/mileage/implement/MileageWriter.java
  src/main/java/university/likelion/wmt/domain/mileage/repository/MileageApplyRepository.java
  src/main/java/university/likelion/wmt/domain/mileage/repository/MileageLogRepository.java
  src/main/java/university/likelion/wmt/domain/mileage/repository/MileageLogRepositoryCustom.java
  src/main/java/university/likelion/wmt/domain/mileage/repository/MileageLogRepositoryImpl.java
  src/main/java/university/likelion/wmt/domain/mileage/service/MileageService.java
Labels: Priority: Critical, Status: Review Needed, Type: Feature

#25 feat: report 도메인에 사용자 속성 부여하는 기능 추가
  src/main/java/university/likelion/wmt/domain/report/dto/response/ReportResponse.java
  src/main/java/university/likelion/wmt/domain/report/service/ReportService.java
Labels: Priority: High, Status: Confirmed, Type: Enhancement
